# Generated by Django 3.2.5 on 2021-07-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(default=1625848404.246498)),
                ('updated_at', models.TextField()),
                ('counted_at', models.IntegerField()),
                ('code', models.CharField(max_length=62)),
                ('preview_img', models.TextField()),
                ('title', models.CharField(max_length=124)),
                ('content', models.TextField()),
                ('date', models.TextField()),
                ('ref', models.URLField()),
            ],
            options={
                'ordering': ['created_at', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Potal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_share', to='news.article')),
            ],
        ),
    ]
