# Generated by Django 3.2.5 on 2021-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1625996243.3620093),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.TextField(null=True),
        ),
    ]
