# Generated by Django 3.2.5 on 2021-07-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20210717_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1626486405.2243776),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_img',
            field=models.TextField(blank=True, default='default.png'),
        ),
    ]
