# Generated by Django 3.2.5 on 2021-07-21 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0036_auto_20210721_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='press',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='press', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1626852114.5764267),
        ),
    ]
