# Generated by Django 3.2.5 on 2021-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_auto_20210721_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpress',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='counted_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1626868912.5773249),
        ),
    ]
