# Generated by Django 3.2.5 on 2021-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_auto_20210721_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1626876922.4006395),
        ),
    ]
