# Generated by Django 3.2.5 on 2021-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_auto_20210721_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpress',
            name='non_press',
            field=models.ManyToManyField(blank=True, related_name='non_press', to='news.Press'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1626930868.7906184),
        ),
    ]
