# Generated by Django 3.2.5 on 2021-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1627263461.331196),
        ),
    ]
