# Generated by Django 3.2.5 on 2021-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0055_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1627797870.4314337),
        ),
    ]
