# Generated by Django 3.2.5 on 2021-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20210713_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1626183006.8448856),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1626183006.8448856),
        ),
    ]
