# Generated by Django 3.2.5 on 2021-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20210713_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1626183167.158251),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1626183167.158251),
        ),
    ]
