# Generated by Django 3.2.5 on 2021-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_auto_20210721_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1626868912.5773249),
        ),
        migrations.AlterField(
            model_name='like',
            name='counted_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1626868912.5773249),
        ),
    ]
