# Generated by Django 3.2.5 on 2021-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_auto_20210721_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1626930868.7906184),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1626930868.7906184),
        ),
    ]
