# Generated by Django 3.2.5 on 2021-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_auto_20210723_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627025250.5287333),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627025250.5287333),
        ),
    ]
