# Generated by Django 3.2.5 on 2021-07-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0039_auto_20210726_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627263493.8873687),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627263493.8873687),
        ),
    ]
