# Generated by Django 3.2.5 on 2021-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0041_auto_20210729_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627569165.7920496),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627569165.7920496),
        ),
    ]
