# Generated by Django 3.2.5 on 2021-08-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_auto_20210729_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627786899.386965),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627786899.386965),
        ),
    ]
