# Generated by Django 3.2.5 on 2021-08-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0043_auto_20210801_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627787033.6126342),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627787033.6126342),
        ),
    ]
