# Generated by Django 3.2.5 on 2021-08-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0045_auto_20210801_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627787240.6133),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627787240.6133),
        ),
    ]
