# Generated by Django 3.2.5 on 2021-08-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0046_auto_20210801_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627787664.4412928),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627787664.4412928),
        ),
    ]
