# Generated by Django 3.2.5 on 2021-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0049_auto_20210801_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627801492.4321542),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627801492.4321542),
        ),
    ]
