# Generated by Django 3.2.5 on 2021-08-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0051_auto_20210801_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1627807876.3511605),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.TextField(default=1627807876.3511605),
        ),
    ]
