# Generated by Django 3.2.5 on 2021-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agreed',
            field=models.BooleanField(default=False, verbose_name='Is agreed'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_detailed',
            field=models.BooleanField(default=False, verbose_name='Is detailed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(default=1625996172.5606937),
        ),
    ]
