# Generated by Django 3.2.5 on 2021-07-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210711_0820'),
        ('user', '0011_auto_20210711_0938'),
    ]

    operations = [
    ]
