# Generated by Django 3.2.5 on 2021-07-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20210726_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(default=1627263493.8873687),
        ),
    ]
