# Generated by Django 3.2.5 on 2021-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20210726_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_liked',
            field=models.BooleanField(default=False, verbose_name='Is_liked'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(default=1627369302.337092),
        ),
    ]
