# Generated by Django 3.2.5 on 2021-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(default=1629215204.6073163),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(default='https://neonews-s3.s3.ap-northeast-2.amazonaws.com/2021004434profile3.png', verbose_name='Profile image'),
        ),
    ]
