# Generated by Django 3.2.5 on 2021-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_auto_20210818_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(default=1630393043.9783988),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(default='https://neonews-s3.s3.ap-northeast-2.amazonaws.com/2021154034profile.png', verbose_name='Profile image'),
        ),
    ]
