# Generated by Django 3.2.5 on 2021-10-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_auto_20210831_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TextField(default=1635153356.824175),
        ),
    ]
